name: Benchmark Core (Moonshot)

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  benchmark-core-moonshot:
    uses: ./.github/workflows/benchmark-reusable.yml
    with:
      script_path: scripts/benchmark-core-moonshot.jl
      julia_version: '1.11'
      julia_arch: x64
      runs_on: '["self-hosted", "Linux", "gpu", "cuda"]'
      runner: 'moonshot'