name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  call:
    if: ${{ !contains(join(github.event.pull_request.labels.*.name, ' '), 'run benchmark') }}
    uses: control-toolbox/CTActions/.github/workflows/documentation.yml@main
