name: Orchestrate Minimal Benchmark and Docs

on:
  pull_request:
    types: [labeled, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  guard:
    runs-on: ubuntu-latest
    outputs:
      should_run: >-
        ${{
          (
            contains(github.event.pull_request.labels.*.name, 'run benchmark minimal')
            || contains(github.event.pull_request.labels.*.name, 'run benchmarks all')
          )
          && github.event.pull_request.base.ref == 'main'
        }}
    steps:
      - run: echo "Guard evaluated to ${{ needs.guard.outputs.should_run || 'N/A' }}"

  benchmarks:
    needs: guard
    if: needs.guard.outputs.should_run == 'true'
    uses: ./.github/workflows/benchmark-minimal.yml
    permissions:
      contents: write
      pull-requests: write

  docs:
    needs: benchmarks
    if: needs.guard.outputs.should_run == 'true'
    uses: control-toolbox/CTActions/.github/workflows/documentation.yml@main
    permissions:
      contents: write
      pull-requests: write
